### ISSUE TITLE
CLJS: non-`js/Error` exceptions not propagated properly

### ISSUE THREAD

**Issue by or** [wilkerlucio/wsscode-async#15]
Howdy, I noticed that in ClojureScript non-`js/Error` objects having been thrown in CLJS or JS code don't work with `go-catch`/`<?` to propagate them upwards, e.g.:
```clj
  (go-catch
   (println :value (try
                     (<?
                      (go-catch
                       (throw (js/Error. "foobar"))))
                     (catch :default e
                       (println :error e)))))
```
works just fine, the inner `go-catch` block propagates the thrown `js/Error`, where it can be caught, the result is:
```
:error #object[Error Error: foobar]
:value nil
```
However, if the thrown object does not derive from `js/Error`, for instance with:
```clj
(go-catch
   (println :value (try
                     (<?
                      (go-catch
                       (throw "foobar")))
                     (catch :default e
                       (println :error e)))))
```
then the error is not propagated, even worse: the string is read from the channel as if it were the return value:
```
:value foobar
```

Looks like this is the reason: https://github.com/wilkerlucio/wsscode-async/blob/163b1cf5c9963d4c798aed4018461abdee754a1d/src/com/wsscode/async/async_cljs.cljs#L36-L46

I realize `js/Error` is the right thing to throw, but there could be a lot of code out there that would break this.

I also realized that there's a potential issue on the flip side: if someone were to return (not throw) a `js/Error` (or `Throwable` in CLJ), then that would be thrown at the next `<?` (in my example simply removing the `throw` around the `js/Error` form demonstrates this, it's the same result). This definitely is an unlikely edge case, but it should be handled correctly.

Thinking about that I wondered whether it wouldn't be better if `wsscode-async` were to wrap all exceptions into its own data structure or object at the seams, so it could properly be separated from actual values on the channels and to separate exception detection from the type of object being thrown, similar to how it is done with `promise->chan` and `consumer-pair`. What do you think?

**Comment by or** [comment]
Ping.

**Comment by wilkerlucio** [comment]
Hello Oliver. I understand the problem, but its not an easy one to change without breaking things. The wrapping is possible but would potentially break users, since it turns things in a different error, if missing to unwrap at some place, it would give the wrong error to the user (one that its not expecting).
