### ISSUE TITLE
Add async-clj/{thread,thread-catch,thread-promise}?

### ISSUE THREAD

**Issue by thenonameguy** [wilkerlucio/wsscode-async#2]
In cases where Pathom resolver would block the go threads it would be nice to have an escape hatch using the async/thread pool with the same safety guarantees.

**Comment by wilkerlucio** [comment]
I like the idea, but I would also say that Pathom is a separated lib and should not drive what this lib does, but thinking as a separated thing could be interesting, I'm not gonna make this, but I could take a PR for it.

About Pathom, if you are using blocking things on resolvers, you should use the Pathom support for thread pools: https://wilkerlucio.github.io/pathom/v2/pathom/2.2.0/connect/thread-pool.html

**Comment by thenonameguy** [comment]
Sure, makes sense. I can provide a PR tomorrow I think.

In the pathom use-case I know about threadpools support, but 99% of my resolvers async/go-blocks. I just need this single resolver to be computed on a separate thread to not block the go thread. Currently I'm using (async/thread)'s backing threadpool for that.

Regardless, this addition should be trivial + useful which is a nice combination :)
